metadata:
  id: lightning-terminal
  category: Lightning Node Management
  name: Lightning Terminal
  version: v0.5.0-alpha
  tagline: The easiest way to manage channel liquidity
  description: "Lightning Terminal is the easiest way to manage inbound and outbound\
    \ liquidity on the Lightning Network. Keep your channels open and the funds flowing.\
    \ It provides a visual interface for interacting with your channels and balances\
    \ using Loop. \n\nNew: Introducing Lightning Pool, a marketplace for Lightning\
    \ channels. You can now earn sats by opening new channels to those looking to\
    \ receive funds on Lightning for a set period of time, or rent a channel to start\
    \ accepting payments instantly. Join the marketplace and start putting your Bitcoin\
    \ to work.\n\nWhy use Pool?\n- Earn a return on Lightning capital\n- Rent a channel\
    \ and start accepting payments instantly\n- Open channels for less with transaction\
    \ batching\n\nWhy use Loop?\n- Add \"inbound liquidity\" to receive payments\n\
    - Reduce transaction fees by recycling and reusing Lightning channels\n- Send\
    \ funds to and from users or services that aren't yet Lightning enabled\n- Configurable\
    \ wait times and \"batching\" allow for further fee savings\n- Refill and offload\
    \ funds from any number of Lightning channels in a single on-chain transaction"
  developer: Lightning Labs
  website: https://lightning.engineering
  dependencies:
  - lnd
  repo: https://github.com/lightninglabs/lightning-terminal
  support: https://github.com/lightninglabs/lightning-terminal/issues/new
  port: 3004
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  - 4.jpg
  path: ''
  defaultPassword: moneyprintergobrrr
containers:
- image: lightninglabs/lightning-terminal:v0.5.0-alpha@sha256:1c9c59fe0316de5d64e89e205f91fb647660a865428daacfe582cb968fd42f87
  user: 1000:1000
  restart: on-failure
  stop_grace_period: 1m
  ports:
  - $APP_LIGHTNING_TERMINAL_PORT:$APP_LIGHTNING_TERMINAL_PORT
  command:
  - --insecure-httplisten=0.0.0.0:$APP_LIGHTNING_TERMINAL_PORT
  - --network="$BITCOIN_NETWORK"
  - --lnd-mode="remote"
  - --remote.lnd.rpcserver=$LND_IP:$LND_GRPC_PORT
  - --remote.lnd.macaroonpath="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
  - --remote.lnd.tlscertpath="/lnd/tls.cert"
  name: web
  data:
  - data:/data
  permissions:
  - lnd
  env:
    HOME: /data
  ip: $APP_LIGHTNING_TERMINAL_IP
