# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

version: '3.7'
services:
  server:
    image: vaultwarden/server:1.22.2@sha256:fe2a236b792fb2304ef50f86f1c25076ac5b2748e1b776fce260ad12ad29188d
    user: 1000:1000
    ports:
    - $APP_VAULTWARDEN_PORT:$APP_VAULTWARDEN_PORT
    environment:
      ROCKET_PORT: ${APP_VAULTWARDEN_PORT}
    volumes:
    - ${APP_DATA_DIR}/data:/data
    networks:
      default:
        ipv4_address: $APP_VAULTWARDEN_IP
    stop_grace_period: 1m
    restart: on-failure
