version: '3.7'
services:
  server:
    image: boypt/cloud-torrent:1.3.4@sha256:a1355e9ac319d523ce1fd6e8d34ab8e4bf0b5476c52bfe244e37fea64f6f4228
    user: 1000:1000
    restart: on-failure
    ports:
    - ${APP_SIMPLE_TORRENT_PORT}:${APP_SIMPLE_TORRENT_PORT}
    command: '--port=${APP_SIMPLE_TORRENT_PORT} --config-path /config/simple-torrent.json

      '
    volumes:
    - ${APP_DATA_DIR}/data/config:/config
    - ${APP_DATA_DIR}/data/downloads:/downloads
    - ${APP_DATA_DIR}/data/torrents:/torrents
    networks:
      default:
        ipv4_address: $APP_SIMPLE_TORRENT_IP
