# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

metadata:
  category: Lightning Node Management
  name: ThunderHub
  version: 0.12.28
  tagline: Take full control of your Lightning node
  description: 'ThunderHub allows you to take full control of your Lightning node
    with a slick and awesome UI. Explore all the options that ThunderHub has to offer,
    from sending and receiving Lightning payments, to checking your node''s health
    statistics, and even more advanced options like channel rebalancing and multi-path
    lightning payments.


    Managing and monitoring your node has never been easier with transaction reports,
    graphs and a huge assortment of different features all bundled inside of this
    great tool.'
  developer: Anthony Potdevin
  website: https://apotdevin.com
  dependencies:
  - lnd
  repo: https://github.com/apotdevin/thunderhub
  support: https://t.me/thunderhub
  port: 3000
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: moneyprintergobrrr
containers:
- image: apotdevin/thunderhub:v0.12.28@sha256:0d987cc6a4a3c0571b5babac7c5a18a96999879d6eb6a8a59815ed0e225dc128
  user: 1000:1000
  ports:
  - $APP_THUNDERHUB_PORT:$APP_THUNDERHUB_PORT
  environment:
    NO_VERSION_CHECK: 'true'
    LOG_LEVEL: debug
    ACCOUNT_CONFIG_PATH: /data/thubConfig.yaml
    YML_ENV_1: $LND_IP:$LND_GRPC_PORT
    TOR_PROXY_SERVER: socks://$TOR_PROXY_IP:$TOR_PROXY_PORT
  name: web
  data:
  - data:/data
  permissions:
  - lnd
  ip: $APP_THUNDERHUB_IP
