metadata:
  id: nextcloud
  category: Files
  name: Nextcloud
  version: 21.0.2
  tagline: Productivity platform that keeps you in control
  description: "Nextcloud puts your data at your fingertips, under your control. Store\
    \ your documents, calendar, contacts and photos on your Umbrel instead of some\
    \ company's data center. Features:\n\n- Mobile and desktop sync \n- Versioning\
    \ and undelete \n- Galleries and activity feed \n- File editing and preview support\
    \ for PDF, images, text files, Open Document, Word files and more. \n- Smooth\
    \ performance and easy user interface. \n- Fine-grained control over access to\
    \ data and sharing capabilities by user and by group.\n\nNote: After logging in\
    \ to Nextcloud please change the password to something secure before sharing the\
    \ address with anyone."
  developer: Nextcloud GmbH
  website: https://nextcloud.com
  dependencies: []
  repo: https://github.com/nextcloud/server
  support: https://help.nextcloud.com/categories
  port: 8081
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /login?user=umbrel
  defaultPassword: moneyprintergobrrr
  torOnly: false
containers:
- image: mariadb:10.5.8@sha256:8040983db146f729749081c6b216a19d52e0973134e2e34c0b4fd87f48bc15b0
  user: 1000:1000
  command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  restart: on-failure
  name: db
  data:
  - data/db:/var/lib/mysql
  env:
  - MYSQL_ROOT_PASSWORD=moneyprintergobrrr
  - MYSQL_PASSWORD=moneyprintergobrrr
  - MYSQL_DATABASE=nextcloud
  - MYSQL_USER=nextcloud
  ip: $APP_NEXTCLOUD_DB_IP
- image: redis:6.2.2-buster@sha256:e10f55f92478715698a2cef97c2bbdc48df2a05081edd884938903aa60df6396
  user: 1000:1000
  restart: on-failure
  name: redis
  data:
  - data/redis:/data
  ip: $APP_NEXTCLOUD_REDIS_IP
- image: nextcloud:22.0.0-apache@sha256:55de721417c16ff110720217406778e16f1b63154d2e8d42fc7913c37dbe6d50
  restart: on-failure
  ports:
  - ${APP_NEXTCLOUD_PORT}:80
  depends_on:
  - db
  - redis
  name: web
  data:
  - data/nextcloud:/var/www/html
  env:
  - MYSQL_HOST=${APP_NEXTCLOUD_DB_IP}
  - REDIS_HOST=${APP_NEXTCLOUD_REDIS_IP}
  - MYSQL_PASSWORD=moneyprintergobrrr
  - MYSQL_DATABASE=nextcloud
  - MYSQL_USER=nextcloud
  - NEXTCLOUD_ADMIN_USER=umbrel
  - NEXTCLOUD_ADMIN_PASSWORD=moneyprintergobrrr
  - NEXTCLOUD_TRUSTED_DOMAINS=${APP_DOMAIN}:${APP_NEXTCLOUD_PORT} ${APP_HIDDEN_SERVICE}
  ip: $APP_NEXTCLOUD_IP
- image: nextcloud:22.0.0-apache@sha256:55de721417c16ff110720217406778e16f1b63154d2e8d42fc7913c37dbe6d50
  restart: on-failure
  entrypoint: /cron.sh
  depends_on:
  - db
  - redis
  name: cron
  data:
  - data/nextcloud:/var/www/html
  ip: $APP_NEXTCLOUD_CRON_IP
