version: '3.7'
services:
  db:
    image: mariadb:10.5.8@sha256:8040983db146f729749081c6b216a19d52e0973134e2e34c0b4fd87f48bc15b0
    user: 1000:1000
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: on-failure
    environment:
    - MYSQL_ROOT_PASSWORD=moneyprintergobrrr
    - MYSQL_PASSWORD=moneyprintergobrrr
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_DB_IP
  redis:
    image: redis:6.2.2-buster@sha256:e10f55f92478715698a2cef97c2bbdc48df2a05081edd884938903aa60df6396
    user: 1000:1000
    restart: on-failure
    volumes:
    - ${APP_DATA_DIR}/data/redis:/data
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_REDIS_IP
  web:
    image: nextcloud:22.0.0-apache@sha256:55de721417c16ff110720217406778e16f1b63154d2e8d42fc7913c37dbe6d50
    restart: on-failure
    ports:
    - ${APP_NEXTCLOUD_PORT}:80
    environment:
    - MYSQL_HOST=${APP_NEXTCLOUD_DB_IP}
    - REDIS_HOST=${APP_NEXTCLOUD_REDIS_IP}
    - MYSQL_PASSWORD=moneyprintergobrrr
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - NEXTCLOUD_ADMIN_USER=umbrel
    - NEXTCLOUD_ADMIN_PASSWORD=moneyprintergobrrr
    - NEXTCLOUD_TRUSTED_DOMAINS=${APP_DOMAIN}:${APP_NEXTCLOUD_PORT} ${APP_HIDDEN_SERVICE}
    depends_on:
    - db
    - redis
    volumes:
    - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_IP
  cron:
    image: nextcloud:22.0.0-apache@sha256:55de721417c16ff110720217406778e16f1b63154d2e8d42fc7913c37dbe6d50
    restart: on-failure
    entrypoint: /cron.sh
    depends_on:
    - db
    - redis
    volumes:
    - ${APP_DATA_DIR}/data/nextcloud:/var/www/html
    networks:
      default:
        ipv4_address: $APP_NEXTCLOUD_CRON_IP
