version: '3.7'
services:
  web:
    image: shahanafarooqui/rtl:0.11.0@sha256:d0cd3d868acab40352bc3c8f4b62e49a7ae833878ac09d64debffdddfc063322
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    ports:
    - $APP_RIDE_THE_LIGHTNING_PORT:$APP_RIDE_THE_LIGHTNING_PORT
    environment:
      PORT: $APP_RIDE_THE_LIGHTNING_PORT
      RTL_CONFIG_PATH: /data
      CHANNEL_BACKUP_PATH: /data/backup
      LN_IMPLEMENTATION: LND
      LN_SERVER_URL: https://$LND_IP:$LND_REST_PORT
      MACAROON_PATH: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK
      CONFIG_PATH: /lnd/lnd.conf
      SWAP_SERVER_URL: https://$APP_RIDE_THE_LIGHTNING_LOOP_IP:8081
      SWAP_MACAROON_PATH: /loop/.loop/$BITCOIN_NETWORK
    volumes:
    - ${LND_DATA_DIR}:/lnd:ro
    - ${APP_DATA_DIR}/loop:/loop
    - ${APP_DATA_DIR}/rtl:/data
    networks:
      default:
        ipv4_address: $APP_RIDE_THE_LIGHTNING_IP
  loop:
    image: louneskmt/loop:v0.12.1-beta@sha256:f57abd0cbccfaa741d6f0eb301421be1649e7dd42c1fc804a7759d7521866436
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    environment:
      HOME: /data
    command:
    - --network=$BITCOIN_NETWORK
    - --lnd.host="$LND_IP:$LND_GRPC_PORT"
    - --lnd.macaroonpath="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
    - --lnd.tlspath="/lnd/tls.cert"
    - --restlisten=0.0.0.0:8081
    volumes:
    - ${LND_DATA_DIR}:/lnd:ro
    - ${APP_DATA_DIR}/loop:/data
    networks:
      default:
        ipv4_address: $APP_RIDE_THE_LIGHTNING_LOOP_IP
