# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

version: '3.7'
services:
  web:
    image: lnbitsdocker/lnbits:3b9401e@sha256:083a7e2d7822bf1a8dd938019ebc044450d74a5b1a9af89dfa5fa695d24ec317
    user: 1000:1000
    init: true
    ports:
    - $APP_LNBITS_PORT:$APP_LNBITS_PORT
    environment:
      LNBITS_BIND: 0.0.0.0:$APP_LNBITS_PORT
      LNBITS_DATA_FOLDER: /data
      LNBITS_BACKEND_WALLET_CLASS: LndWallet
      LND_GRPC_ENDPOINT: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      LND_GRPC_CERT: /lnd/tls.cert
      LND_GRPC_MACAROON: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon
      LNBITS_SITE_TITLE: LNbits - Citadel
      LNBITS_DEFAULT_WALLET_NAME: LNbits wallet
      LNBITS_DISABLED_EXTENSIONS: amilk
    volumes:
    - ${LND_DATA_DIR}:/lnd:ro
    - ${APP_DATA_DIR}/data:/data
    networks:
      default:
        ipv4_address: $APP_LNBITS_IP
    stop_grace_period: 1m
    restart: on-failure
