metadata:
  id: samourai-server
  category: Wallet Servers
  name: Samourai Server (Broken)
  version: 1.10.1
  tagline: We're sorry, but Samourai isn't working right now because of a bug in Umbrel
    and Citadel.
  description: 'Samourai Server is an exclusive Umbrel app that runs Samourai Dojo
    and Whirlpool backing servers, and provides you easy step-by-step instructions
    to connect your Samourai Wallet to them. Samourai Wallet is unrivaled in transaction
    privacy, but its default configuration is still subject to network level privacy
    loss.


    By default, Samourai Wallet will connect to its centrally controlled Dojo hosted
    in Iceland. By hosting your own Samourai Server, you can bypass its servers completely
    when using Samourai Wallet or Sentinel, and gain total financial sovereignty without
    any complexity.


    Bundles Whirlpool CLI v0.10.11.'
  developer: Samourai
  website: https://samouraiwallet.com
  dependencies:
  - bitcoind
  repo: https://github.com/louneskmt/umbrel-samourai-dojo/tree/v1.10.1-umbrel
  support: https://t.me/SamouraiWallet
  port: 3005
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: ''
containers:
- image: mariadb:10.5.8@sha256:8040983db146f729749081c6b216a19d52e0973134e2e34c0b4fd87f48bc15b0
  init: true
  restart: on-failure
  stop_grace_period: 5m
  user: 1000:1000
  environment:
    MYSQL_DATABASE: samourai-main
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_USER: samourai
    MYSQL_PASSWORD: password
  name: db
  data:
  - mysql/update-db.sh:/update-db.sh
  - mysql/mysql-dojo.cnf:/etc/mysql/conf.d/mysql-dojo.cnf
  - mysql/db-scripts:/docker-entrypoint-initdb.d
  - mysql/data:/var/lib/mysql
  ip: $APP_SAMOURAI_SERVER_DB_IP
- image: louneskmt/dojo-nodejs:1.10.1@sha256:d1460df18df091837718fcd0a6d3850e2f1a4a49da5914a697648c40d5477184
  init: true
  restart: on-failure
  command: /home/node/app/wait-for-it.sh db:3306 --timeout=720 --strict -- /home/node/app/restart.sh
  user: 1000:1000
  environment:
    COMMON_BTC_NETWORK: $BITCOIN_NETWORK
    DOJO_NODEJS_VERSION_TAG: 1.10.1
    NET_DOJO_TOR_IPV4: $TOR_PROXY_IP
    NET_DOJO_TOR_PORT: $TOR_PROXY_PORT
    NET_DOJO_MYSQL_IPV4: $APP_SAMOURAI_SERVER_DB_IP
    MYSQL_DATABASE: samourai-main
    MYSQL_USER: samourai
    MYSQL_PASSWORD: password
    NODE_GAP_EXTERNAL: 100
    NODE_GAP_INTERNAL: 100
    NODE_ADDR_FILTER_THRESHOLD: 1000
    NODE_ADDR_DERIVATION_MIN_CHILD: 2
    NODE_ADDR_DERIVATION_MAX_CHILD: 2
    NODE_ADDR_DERIVATION_THRESHOLD: 10
    NODE_TXS_SCHED_MAX_ENTRIES: 10
    NODE_TXS_SCHED_MAX_DELTA_HEIGHT: 18
    NODE_JWT_ACCESS_EXPIRES: 900
    NODE_JWT_REFRESH_EXPIRES: 7200
    NODE_PREFIX_STATUS: status
    NODE_PREFIX_SUPPORT: support
    NODE_PREFIX_STATUS_PUSHTX: status
    NODE_TRACKER_MEMPOOL_PERIOD: 10000
    NODE_TRACKER_UNCONF_TXS_PERIOD: 300000
    NODE_ACTIVE_INDEXER: local_indexer
    NODE_FEE_TYPE: ECONOMICAL
    NODE_API_KEY: $SAMOURAI_SERVER_NODE_API_KEY
    NODE_ADMIN_KEY: $SAMOURAI_SERVER_NODE_ADMIN_KEY
    NODE_JWT_SECRET: $SAMOURAI_SERVER_NODE_JWT_SECRET
    BITCOIND_IP: $BITCOIN_IP
    BITCOIND_RPC_PORT: $BITCOIN_RPC_PORT
    BITCOIND_RPC_USER: $BITCOIN_RPC_USER
    BITCOIND_RPC_PASSWORD: $BITCOIN_RPC_PASS
    BITCOIND_ZMQ_RAWTXS: $BITCOIN_ZMQ_RAWTX_PORT
    BITCOIND_ZMQ_BLK_HASH: $BITCOIN_ZMQ_HASHBLOCK_PORT
    EXPLORER_INSTALL: 'off'
    INDEXER_IP: $ELECTRUM_IP
    INDEXER_RPC_PORT: $ELECTRUM_PORT
    INDEXER_BATCH_SUPPORT: inactive
  depends_on:
  - db
  name: node
  permissions:
  - bitcoind
  ip: $APP_SAMOURAI_SERVER_NODE_IP
- image: louneskmt/whirlpool:0.10.11@sha256:a7cfb9e287aa5f2e4137a5d2fdddbfd348624e24e7dd7bed7fa0f4e2e22734d5
  init: true
  restart: on-failure
  user: 1000:1000
  command:
  - --listen
  - --cli.apiKey=$SAMOURAI_SERVER_WHIRLPOOL_API_KEY
  - --cli.api.http-enable=true
  - --cli.api.http-port=$APP_SAMOURAI_SERVER_WHIRLPOOL_PORT
  - --cli.tor=true
  - --cli.torConfig.coordinator.enabled=true
  - --cli.torConfig.coordinator.onion=true
  - --cli.torConfig.backend.enabled=false
  - --cli.torConfig.backend.onion=false
  - --cli.mix.liquidityClient=true
  - --cli.mix.clientsPerPool=1
  - --resync
  environment:
    WHIRLPOOL_BITCOIN_NETWORK: $BITCOIN_NETWORK
    WHIRLPOOL_DOJO: 'on'
    WHIRLPOOL_DOJO_IP: $APP_SAMOURAI_SERVER_IP
  name: whirlpool
  data:
  - whirlpool:/home/whirlpool/.whirlpool-cli
  permissions:
  - bitcoind
  ip: $APP_SAMOURAI_SERVER_WHIRLPOOL_IP
- image: nginx:1.19-alpine@sha256:c2ce58e024275728b00a554ac25628af25c54782865b3487b11c21cafb7fabda
  init: true
  restart: on-failure
  command: /bin/sh -c "envsubst < /var/www/connect/js/conf.template.js > /var/www/connect/js/conf.js
    && /wait-for node:8080 --timeout=720 -- nginx"
  environment:
    COMMON_BTC_NETWORK: $BITCOIN_NETWORK
    DOJO_LOCAL_PORT: $APP_SAMOURAI_SERVER_DOJO_PORT
    DOJO_HIDDEN_SERVICE: $SAMOURAI_SERVER_DOJO_HIDDEN_SERVICE
    WHIRLPOOL_HIDDEN_SERVICE: $SAMOURAI_SERVER_WHIRLPOOL_HIDDEN_SERVICE
    NODE_PREFIX_SUPPORT: support
    NODE_ADMIN_KEY: $SAMOURAI_SERVER_NODE_ADMIN_KEY
    WHIRLPOOL_API_KEY: $SAMOURAI_SERVER_WHIRLPOOL_API_KEY
  ports:
  - $APP_SAMOURAI_SERVER_DOJO_PORT:80
  - $APP_SAMOURAI_SERVER_CONNECT_PORT:8081
  depends_on:
  - node
  name: nginx
  data:
  - nginx/connect:/var/www/connect
  - nginx/connect.conf:/etc/nginx/sites-enabled/connect.conf
  - nginx/${BITCOIN_NETWORK}.conf:/etc/nginx/sites-enabled/dojo.conf
  - nginx/nginx.conf:/etc/nginx/nginx.conf
  - nginx/wait-for:/wait-for
  permissions:
  - bitcoind
  ip: $APP_SAMOURAI_SERVER_IP
