metadata:
  id: btc-rpc-explorer
  category: Explorers
  name: BTC RPC Explorer
  version: 3.1.1
  tagline: Simple, database-free blockchain explorer
  description: 'BTC RPC Explorer is a full-featured, self-hosted explorer for the
    Bitcoin blockchain. With this explorer, you can explore not just the blockchain
    database, but also explore the functional capabilities of your Umbrel.


    It comes with a network summary dashboard, detailed view of blocks, transactions,
    addresses, along with analysis tools for viewing stats on miner activity, mempool
    summary, with fee, size, and age breakdowns. You can also search by transaction
    ID, block hash/height, and addresses.


    It''s time to appreciate the "fullness" of your node.'
  developer: Dan Janosik
  website: https://explorer.btc21.org
  dependencies:
  - bitcoind
  - electrum
  repo: https://github.com/janoside/btc-rpc-explorer
  support: https://github.com/janoside/btc-rpc-explorer/discussions
  port: 3002
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: ''
containers:
- image: getumbrel/btc-rpc-explorer:v3.1.1@sha256:df6810c00cb026a1d8cadaba2f4926f1310b996eebe006d29929fece5bff63bf
  restart: on-failure
  stop_grace_period: 1m
  ports:
  - $APP_BTC_RPC_EXPLORER_PORT:$APP_BTC_RPC_EXPLORER_PORT
  environment:
    BTCEXP_HOST: 0.0.0.0
    BTCEXP_BITCOIND_HOST: $BITCOIN_IP
    BTCEXP_BITCOIND_PORT: $BITCOIN_RPC_PORT
    BTCEXP_BITCOIND_USER: $BITCOIN_RPC_USER
    BTCEXP_BITCOIND_PASS: $BITCOIN_RPC_PASS
    BTCEXP_ADDRESS_API: electrumx
    BTCEXP_ELECTRUMX_SERVERS: tcp://$ELECTRUM_IP:$ELECTRUM_PORT
    DEBUG: btcexp:*,electrumClient
    BTCEXP_SLOW_DEVICE_MODE: 'true'
    BTCEXP_NO_INMEMORY_RPC_CACHE: 'true'
    BTCEXP_PRIVACY_MODE: 'true'
    BTCEXP_NO_RATES: 'true'
    BTCEXP_RPC_ALLOWALL: 'false'
    BTCEXP_BASIC_AUTH_PASSWORD: ''
  name: web
  ip: $APP_BTC_RPC_EXPLORER_IP
