version: '3.7'
services:
  server:
    image: homeassistant/home-assistant:2021.9.4@sha256:282a4038bb8c5460835c945a1d1c15019a6188de81046c79d4c094ab6579dde4
    ports:
    - ${APP_HOME_ASSISTANT_PORT}:8123
    volumes:
    - ${APP_DATA_DIR}/data:/config
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
    stop_grace_period: 1m
    restart: on-failure
