# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
# 
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# Warning: it's not recommended to modify these files directly. Any
# modifications you make can break the functionality of your node. These files
# are automatically reset with every update.

verbose = 2
network = "bitcoin"
db_dir = "/data/db"
daemon_dir = "/bitcoin"
daemon_rpc_addr = "<bitcoin-ip>:<bitcoin-rpc-port>"
daemon_p2p_addr = "<bitcoin-ip>:<bitcoin-p2p-port>"
electrum_rpc_addr = "0.0.0.0:<electrum-port>"
server_banner = "Umbrel v<umbrel-version>"
