# SPDX-FileCopyrightText: 2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

version: "3.7"

networks:
  default:
    name: umbrel_main_network
    external: true
