# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app/app-standard-v1.json

version: 1

metadata:
  category: Explorers
  name: Mempool
  version: 2.2.2
  tagline: A mempool visualizer, explorer and fee estimator
  description: 'Mempool is the official self-hosted version of the fully featured
    explorer, visualizer, fee estimator, and API service running on mempool.space,
    an open source project developed and operated for the benefit of the Bitcoin community,
    with a focus on the emerging transaction fee market to help our transition into
    a multi-layer ecosystem.


    Features:


    - Live dashboard visualizing the mempool and blockchain

    - Live transaction tracking

    - Search any transaction, block or address

    - Fee estimations

    - Mempool historical data

    - TV View for larger displays as a TV in a cafe or bar

    - View transaction scripts and op_return messages

    - Audio notifications on transaction confirmed and address balance change

    - Multiple languages support

    - JSON APIs'
  developer: mempool.space
  website: https://mempool.space/about
  dependencies:
  - electrum
  - bitcoind
  repo: https://github.com/mempool/mempool
  support: https://t.me/mempoolspace
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg

containers:
- name: main
  image: mempool/frontend:v2.2.2@sha256:515b9a3ab3cc593fe599393b316d4d016335801fbba02ef8c6bb38082597f7cc
  user: 1000:1000
  init: true
  command: ./wait-for mariadb:3306 --timeout=720 -- nginx -g 'daemon off;'
  environment:
    FRONTEND_HTTP_PORT: $APP_MEMPOOL_MAIN_PORT
    BACKEND_MAINNET_HTTP_HOST: $APP_MEMPOOL_API_IP

- name: api
  image: mempool/backend:v2.2.2@sha256:c758345017587dd9e42047528cf6cd71ceae70cebd1a09ce875959259612a2ee
  user: 1000:1000
  init: true
  command: ./wait-for-it.sh mariadb:3306 --timeout=720 --strict -- ./start.sh
  environment:
    RPC_HOST: $BITCOIN_IP
    RPC_PORT: $BITCOIN_RPC_PORT
    RPC_USER: $BITCOIN_RPC_USER
    RPC_PASS: $BITCOIN_RPC_PASS
    ELECTRUM_HOST: $ELECTRUM_IP
    ELECTRUM_PORT: $ELECTRUM_PORT
    ELECTRUM_TLS: 'false'
    MYSQL_HOST: $APP_MEMPOOL_MARIADB_IP
    MYSQL_PORT: '3306'
    MYSQL_DATABASE: mempool
    MYSQL_USER: mempool
    MYSQL_PASS: mempool
    BACKEND_MAINNET_HTTP_PORT: '8999'
    CACHE_DIR: /backend/cache
    MEMPOOL_CLEAR_PROTECTION_MINUTES: '20'
  data:
  - data:/backend/cache
  permissions:
  - electrum
  - bitcoind

- name: mariadb
  image: mariadb:10.6.4@sha256:4bbee12b1adf299211f844ebbe89563675c46965470dcfa40f5278d63c56d030
  user: 1000:1000
  environment:
    MYSQL_DATABASE: mempool
    MYSQL_USER: mempool
    MYSQL_PASSWORD: mempool
    MYSQL_ROOT_PASSWORD: moneyprintergobrrr
  data:
  - mysql/db-scripts:/docker-entrypoint-initdb.d
  - mysql/data:/var/lib/mysql
