metadata:
  id: gitea
  category: Development
  name: Gitea
  version: 1.14.3
  tagline: A painless self-hosted Git service
  description: 'Gitea is a painless self-hosted Git service. It is similar to GitHub,
    Bitbucket, and GitLab. It is a community managed lightweight code hosting solution
    written in Go. Gitea''s minimal requirements allow it to run seamlessly on inexpensive
    hardware like a Raspberry Pi. Features:


    - Fully self-hosted and private

    - Issue tracker

    - Account/Organization/Repository management

    - Tor support

    - Repository Git hooks/deploy keys

    - Repository issues, pull requests and wiki

    - Add/Remove repository collaborators

    - Gravatar and custom source

    - Admin panel'
  developer: Gitea
  website: https://gitea.io/en-us/
  dependencies: []
  repo: https://github.com/go-gitea/gitea
  support: https://discourse.gitea.io
  port: 8085
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: ''
  torOnly: false
containers:
- image: gitea/gitea:1.14.5-rootless@sha256:6ff3d1e527d65d285fa248920e36b381e08f7c6f408a8883230751ff2a0c0823
  user: 1000:1000
  restart: on-failure
  ports:
  - ${APP_GITEA_PORT}:${APP_GITEA_PORT}
  - ${APP_GITEA_SSH_PORT}:${APP_GITEA_SSH_PORT}
  name: server
  data:
  - data/gitea/config:/etc/gitea
  - data/gitea/data:/var/lib/gitea
  env:
    GITEA__security__INSTALL_LOCK: 'true'
    GITEA__server__DOMAIN: ${APP_DOMAIN}
    GITEA__server__HTTP_PORT: ${APP_GITEA_PORT}
    GITEA__server__SSH_DOMAIN: ${APP_DOMAIN}
    GITEA__server__SSH_PORT: ${APP_GITEA_SSH_PORT}
    GITEA__server__SSH_LISTEN_PORT: ${APP_GITEA_SSH_PORT}
    GITEA__server__START_SSH_SERVER: 'true'
    GITEA__database__DB_TYPE: mysql
    GITEA__database__HOST: ${APP_GITEA_DB_IP}:3306
    GITEA__database__NAME: gitea
    GITEA__database__USER: gitea
    GITEA__database__PASSWD: moneyprintergobrrr
- image: mariadb:10.5.8@sha256:8040983db146f729749081c6b216a19d52e0973134e2e34c0b4fd87f48bc15b0
  user: 1000:1000
  restart: on-failure
  name: db
  data:
  - data/db:/var/lib/mysql
  env:
    MYSQL_ROOT_PASSWORD: gitea
    MYSQL_USER: gitea
    MYSQL_PASSWORD: moneyprintergobrrr
    MYSQL_DATABASE: gitea
